FROM amd64/alpine:3.6@sha256:36c3a913e62f77a82582eb7ce30d255f805c3d1e11d58e1f805e14d33c2bc5a5

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Alpine" \
  org.opencontainers.image.vendor="Thomas Boerger"

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay ./overlay-amd64 /

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec s6 && \
  curl -sSLo /usr/bin/wait-for-it https://raw.githubusercontent.com/thegeeklab/wait-for/d17c23172a39d7555f184d916881aeae6d446a22/wait-for && \
  chmod +x /usr/bin/wait-for-it && \
  rm -rf /var/cache/apk/*
