FROM arm32v6/alpine:3.9@sha256:2212b66d3d2d6bfde42b5a7308b9079eaceff95a1aff44c6001e933674cabfb3

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Alpine" \
  org.label-schema.version="3.9" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay ./overlay-arm32v6 /

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec s6 && \
  rm -rf /var/cache/apk/*
