FROM arm64v8/alpine:3.11@sha256:eb8e13f2b7decd9017fa0ba597294afb176b18e4fc89f64eb4e884a8e53b36d2

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Alpine" \
  org.opencontainers.image.vendor="Thomas Boerger"

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay ./overlay-arm64v8 /

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec s6 && \
  curl -sSLo /usr/bin/wait-for-it https://raw.githubusercontent.com/thegeeklab/wait-for/d17c23172a39d7555f184d916881aeae6d446a22/wait-for && \
  chmod +x /usr/bin/wait-for-it && \
  rm -rf /var/cache/apk/*
