FROM amd64/alpine:3.23@sha256:25735e5ed514a296d2c8d52d458c2f74b081169d8848f0614b4fa24a3aefc843 AS build

RUN apk add -U curl ca-certificates

# renovate: datasource=github-releases depName=thegeeklab/wait-for
ENV WAITFOR_VERSION=0.4.3

RUN curl -sSLo /tmp/wait-for-it https://github.com/thegeeklab/wait-for/releases/download/v${WAITFOR_VERSION}/wait-for && \
  chmod +x /tmp/wait-for-it && \
  /tmp/wait-for-it --help 2>/dev/null

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION=5.0.0

RUN curl -sSLo /tmp/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-amd64 && \
  chmod +x /tmp/gomplate && \
  /tmp/gomplate --help >/dev/null

FROM amd64/alpine:3.22@sha256:49e9370a0b8c081f75f408e069c417b0a3ec0b41e5878bed4b0a34bc52e7c5c9

ENV CRON_ENABLED=false
ENV TERM=xterm

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay /

RUN sed -i 's/\r$//' /usr/bin/entrypoint && \
  chmod +x /usr/bin/entrypoint

COPY --from=build /tmp/wait-for-it /usr/bin/
COPY --from=build /tmp/gomplate /usr/bin/

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec tini s6 xz tzdata && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
