FROM amd64/alpine:3.23@sha256:f834b19149456f530d448cd8942f2c8b66e240976fd1397113ae542fa8cabf06 AS build

RUN apk add -U curl ca-certificates

# renovate: datasource=github-releases depName=thegeeklab/wait-for
ENV WAITFOR_VERSION=0.4.4

RUN curl -sSLo /tmp/wait-for-it https://github.com/thegeeklab/wait-for/releases/download/v${WAITFOR_VERSION}/wait-for && \
  chmod +x /tmp/wait-for-it && \
  /tmp/wait-for-it --help 2>/dev/null

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION=5.1.0

RUN curl -sSLo /tmp/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-amd64 && \
  chmod +x /tmp/gomplate && \
  /tmp/gomplate --help >/dev/null

FROM amd64/alpine:3.22@sha256:5546634cd0e4e1f56b9abfc1a6548d7cf1a5b29a73767bf416321ff2a82e66cd

ENV CRON_ENABLED=false
ENV TERM=xterm

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay /

RUN sed -i 's/\r$//' /usr/bin/entrypoint && \
  chmod +x /usr/bin/entrypoint

COPY --from=build /tmp/wait-for-it /usr/bin/
COPY --from=build /tmp/gomplate /usr/bin/

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec tini s6 xz tzdata && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
