FROM alpine:3.15@sha256:ceeae2849a425ef1a7e591d8288f1a58cdf1f4e8d9da7510e29ea829e61cf512 AS build

RUN apk add -U curl ca-certificates

# renovate: datasource=github-releases depName=thegeeklab/wait-for
ENV WAITFOR_VERSION=0.2.0

RUN curl -sSLo /tmp/wait-for-it https://github.com/thegeeklab/wait-for/releases/download/v${WAITFOR_VERSION}/wait-for && \
  chmod +x /tmp/wait-for-it

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION=3.10.0

RUN curl -sSLo /tmp/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-amd64 && \
  chmod +x /tmp/gomplate

FROM alpine:3.15@sha256:ceeae2849a425ef1a7e591d8288f1a58cdf1f4e8d9da7510e29ea829e61cf512

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay /

COPY --from=build /tmp/wait-for-it /usr/bin/
COPY --from=build /tmp/gomplate /usr/bin/

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec tini s6 xz && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
