FROM amd64/alpine:3.21@sha256:e12e320987960bf6c08df76494ab095970b76de90f972682880e2ab9c60cc4de AS build

RUN apk add -U curl ca-certificates

# renovate: datasource=github-releases depName=thegeeklab/wait-for
ENV WAITFOR_VERSION=0.4.3

RUN curl -sSLo /tmp/wait-for-it https://github.com/thegeeklab/wait-for/releases/download/v${WAITFOR_VERSION}/wait-for && \
  chmod +x /tmp/wait-for-it && \
  /tmp/wait-for-it --help 2>/dev/null

# renovate: datasource=github-releases depName=hairyhenderson/gomplate
ENV GOMPLATE_VERSION=5.0.0

RUN curl -sSLo /tmp/gomplate https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-amd64 && \
  chmod +x /tmp/gomplate && \
  /tmp/gomplate --help >/dev/null

FROM amd64/alpine:3.21@sha256:e12e320987960bf6c08df76494ab095970b76de90f972682880e2ab9c60cc4de

ENV CRON_ENABLED=false
ENV TERM=xterm

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay /

RUN sed -i 's/\r$//' /usr/bin/entrypoint && \
  chmod +x /usr/bin/entrypoint

COPY --from=build /tmp/wait-for-it /usr/bin/
COPY --from=build /tmp/gomplate /usr/bin/

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec tini s6 xz tzdata && \
  update-ca-certificates && \
  rm -rf /var/cache/apk/*
