FROM arm64v8/alpine:3.12@sha256:32fe23b96d3bc375d94f23a656741b70eae01db1a1e8856ea1844fa99c32e0a9

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Alpine" \
  org.opencontainers.image.vendor="Thomas Boerger"

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay ./overlay-arm64v8 /

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec tini s6 && \
  curl -sSLo /usr/bin/wait-for-it https://raw.githubusercontent.com/thegeeklab/wait-for/d17c23172a39d7555f184d916881aeae6d446a22/wait-for && \
  chmod +x /usr/bin/wait-for-it && \
  rm -rf /var/cache/apk/*
