FROM arm64v8/alpine:3.9@sha256:65faa9b36980bbcca914e5e6d3baa005261be9b0f305546553d670a6de939bcb

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Alpine" \
  org.label-schema.version="3.9" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay ./overlay-arm64v8 /

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec s6 && \
  rm -rf /var/cache/apk/*
