FROM alpine:3.8@sha256:dad671370a148e9d9573e3e10a9f8cc26ce937bea78f3da80b570c2442364406

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Alpine" \
  org.label-schema.version="3.8" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENV CRON_ENABLED false
ENV TERM xterm

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["bash"]

COPY ./overlay ./overlay-amd64 /

RUN apk update && \
  apk upgrade -a || apk fix && \
  apk add ca-certificates curl bash bash-completion ncurses vim tar rsync shadow su-exec s6 && \
  rm -rf /var/cache/apk/*
